name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      deploy_url: ${{ steps.set-output.outputs.deploy_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _build_site

      - name: "Debug: Built files"
        run: ls -alR _build_site

      - name: "Prepare deploy structure"
        id: set-output
        run: |
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"

          if [ "$GITHUB_REF_NAME" = "master" ]; then
            DEPLOY_URL="https://triorb-inc.github.io/TriOrb-AMR-Documents/"
            mkdir -p _build_site_branch
            rsync -av _build_site/ _build_site_branch/
          else
            DEPLOY_URL="https://triorb-inc.github.io/TriOrb-AMR-Documents/branch/$GITHUB_REF_NAME/"
            mkdir -p _build_site_branch/branch/$GITHUB_REF_NAME
            rsync -av _build_site/ _build_site_branch/branch/$GITHUB_REF_NAME/
          fi

          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployment URL: $DEPLOY_URL"

      - name: "Debug: Prepared build output"
        run: ls -alR _build_site_branch

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-content
          path: _build_site_branch/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-content
          path: ./deploy_dir

      - name: "Debug: Downloaded deploy_dir"
        run: ls -alR ./deploy_dir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./deploy_dir
