name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ "**" ]  # 全ブランチ対象

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _build_site

      - name: Debug build output
        run: ls -R _build_site

      - name: Prepare branch-specific path and set deploy URL
        run: |
          echo "branch_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV

          if [ "$GITHUB_REF_NAME" = "master" ]; then
            echo "publish_dir=_build_site" >> $GITHUB_ENV
            echo "deploy_url=https://triorb-inc.github.io/TriOrb-AMR-Documents/" >> $GITHUB_ENV
          else
            export TARGET=_build_site_branch/branch/$GITHUB_REF_NAME
            mkdir -p "$TARGET"
            rsync -av _build_site/ "$TARGET/"
            echo "publish_dir=$TARGET" >> $GITHUB_ENV
            echo "deploy_url=https://triorb-inc.github.io/TriOrb-AMR-Documents/branch/$GITHUB_REF_NAME/" >> $GITHUB_ENV
          fi

      - name: Show deployment URL
        run: echo "✅ Deployed to: ${{ env.deploy_url }}"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.publish_dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ${{ env.publish_dir }}
